### ISSUE TITLE
Selecting 'Monochrome accent' for the Bar chart of RAM doesn't work as expected

### ISSUE THREAD

**Issue by protik77** [exelban/stats#1015]
**Describe the bug**
Selected 'Monochrome accent' from 'System accent' for the Bar chart of the RAM. But that didn't change the colors. The color remained as 'System accent'.

Example below.
<img width="525" alt="RAM_bar_chart_monochrome" src="https://user-images.githubusercontent.com/1991215/181876958-1ac0a556-596f-4817-953b-eaba02c1c57c.png">

**Details:**
 - Device: MacBook Pro (13-inch, M1, 2020)
 - macOS: 12.5
 - Application version: 2.7.27

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yes, it does not change the colors. But it does not remain colors as `System accent`. If you have enabled the `Split the value (App/Wired/Compressed)` option the colors are predefined. And could not be changed. Because they must match the colors of the values in the popup (App/Wired/Compressed).

TL.DR: when you have enabled the `Split the value (App/Wired/Compressed)` option the colors are predefined and colors could not be changed.

**Comment by jollino** [comment]
Hi, apologies for resurrecting an old issue. I was wondering if the "Split the value" option was removed at some point (or moved elsewhere), as I can't seem to find it anywhere on 2.11.58. Would one just manually set all types to the same color? Thanks in advance!

**Comment by exelban** [comment]
@jollino you need to have enabled bar chart widget to see it
