### ISSUE TITLE
Can you provide a python JSON API to read the running data of stats? 

### ISSUE THREAD

**Issue by LRF520** [exelban/stats#1057]
The total memory data of the GPU and the memory data of the GPU that has been used are also important, but the tool does not seem to display these two kinds of data.

Great! Can you provide a python JSON API to read the running data of stats? I think this can help everyone to conduct personalized monitoring. Thank you!

**Comment by exelban** [comment]
Hi. Do you know how to get this data?

Nope, I will not add an API for that. First of all, there are apps that already do it. Even in python, you have libs that allow doing that. The next problem in theory cannot be just rest, because I suppose someone will need this data mostly for some internal logging. And firing the endpoint every 1s it's not a good idea. The most preferable way is some live connection: ws or some king of the queue. That allows you to subscribe to the data. And I'm not sure will not add that. Because it requires a lot of work, and I don't see a reason for that. As I said before, you can easily collect the data in the preferable language.
Maybe someday I will add historical data to the app, and it will require some db. And it allows grabbing the data from the db.

TL.DR. Nope, it will be not added.
