### ISSUE TITLE
ICMP not working

### ISSUE THREAD

**Issue by almottier** [exelban/stats#1111]
**Describe the bug**
I am just trying the new ICMP feature. It stays red but I have an internet connection over Wifi. I tried forcing Wifi interface in the settings but I have the same result.

<img width="768" alt="Screenshot 2022-10-06 at 16 44 55" src="https://user-images.githubusercontent.com/5426740/194316201-74f248cf-d01e-472e-9c96-c218598ae5b4.png">

**Details:**
 - Device: MacBook Pro (14-inch, 2021)
 - macOS: 12.6 (21G115)
 - Application version: 2.7.37

**Comment by exelban** [comment]
@luckman212 I need to add logging to the file. So I will post a new build. Thanks.

**Comment by exelban** [comment]
ok, there is a debug build. It writes some logs related to the ICMP to the file `Documents/log.txt`. There must be no sensitive data inside this log. Please share the logs to better understand why it does not work properly.

[Stats.dmg.zip](https://github.com/exelban/stats/files/9726376/Stats.dmg.zip)

**Comment by luckman212** [comment]
Ok, got it 👍 

## Video

on left is a continuous ping to `9.9.9.9` and on right is `tail -f log.txt` -- you can see Stats red dot in menubar...

https://user-images.githubusercontent.com/1992842/194359492-372dc544-e49e-4a8e-887b-c1c413186c25.mp4

## Log

[log.txt](https://github.com/exelban/stats/files/9726471/log.txt)

## Settings

<img width="720" alt="image" src="https://user-images.githubusercontent.com/1992842/194359040-c71c4861-8491-4edc-b834-fc3af399f9fb.png">

<img width="280" alt="image2" src="https://user-images.githubusercontent.com/1992842/194358996-c8fcd5a2-a4b2-41ae-b754-59d970ca2611.png">

**Comment by exelban** [comment]
Hmm, very strange. Could you please try this build (it collects more information about why the signal is false)?
[Stats.dmg.zip](https://github.com/exelban/stats/files/9726536/Stats.dmg.zip)

**Comment by exelban** [comment]
Yeap, exactly. The packets that are coming to the Stats most probably are from the terminal. In theory, I can disable fingerprint checks. But I'm not sure if it's ok. Because, for example, there could be some internal ICMP packets from the local network. And this check will lose any sense.

@almottier please check if you have the same situation.

**Comment by luckman212** [comment]
I don't think fingerprint should be disabled, I haven't looked at the code because I have to leave now but have you taken a look at https://github.com/samiyr/SwiftyPing ? Maybe some ideas there that you can borrow from.

Because when I compiled that Test project, it works fine pinging at the same time as Terminal...

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1992842/194373765-b5b9c6e2-8869-4791-94bc-44908bbcc381.png">

**Comment by almottier** [comment]
> @almottier please check if you have the same situation.

I confirm I have the same situation. As soon as I ping from a terminal, I start to have a red dot in Stats.

**Comment by exelban** [comment]
Thanks, I will try to fix that.

**Comment by luckman212** [comment]
I compiled a build based on the latest `master` branch, and confirm that the fix is working @exelban

**Comment by luckman212** [comment]
Anyone else notice that this is issue #`1111` and the default ICMP target is also `1.1.1.1`... cosmic irony? 👻
