### ISSUE TITLE
[FR] Add text labels beneath CPU usage bars in popup 

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#1313]
#### Summary

It would be nice (imo) if there were small labels beneath the CPU core usage levels in the popup to easily identify which are the P/E cores. Example below.

#### Mockup

<img src=https://user-images.githubusercontent.com/1992842/218141995-c7a8aae4-a8e6-4681-9d0a-9a913e9ef400.png width=280>

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Nope, I'm sure I will not add a description like this. First of all these charts were just a quick solution to my needs. 
I don't think taking space for a text that tells nothing is a good idea. Maybe I will add a tooltip on hover. But not in the near future because it requires quite a lot of work.

**Comment by luckman212** [comment]
@exelban Well I can't force you but, a little disappointed that you're abruptly closing without even letting people vote for if they'd find this useful. I see a couple of people upvoted it already, so apparently I'm not the only one who has difficulty remembering which color represents which core.

I'm sponsoring this project to support you and would appreciate at least leaving it open to consideration as a future toggle.

**Comment by exelban** [comment]
First of all. Did you read my answer? Especially the part where I say that I will add a tooltip that will indicate the type of core.
Second. Please consider stopping sponsoring me if you expect that I will implement the features that you "want". I don't see any reason to leave this issue open forever because I already know that I will not implement that like that.

PS: there is only one way how Stats represents different core types: first is efficiency, and after is performance.

**Comment by luckman212** [comment]
🤷‍♂️  No offense was intended! Yes I did read your reply, I was trying to let you know that I agree, a tooltip would be a fine solution.

I won't stop sponsoring, because I do love Stats and this is a minor thing. It was just a suggestion. If you don't want to do it, I think I already said _"I can't force you"_ and no, of course I don't expect you to implement every feature I want for pennies a day.

I hope it's clear from my participation over the years that I am very appreciative of the work you've done here and this amazing app which you give away. But again, _Thank you_.

![fecbfb696cc56363f21ac720c4001ff61e9964a6](https://user-images.githubusercontent.com/1992842/219980425-55038c5d-1a80-40f7-b1da-047b1e8efa05.png)

![b56471705a04a624a4a4e5bec921ccbac0eeb4c1](https://user-images.githubusercontent.com/1992842/219980435-4cdd9a37-619d-450c-b11c-303bbcf81025.png)

![1648a707fcb8332ea8522c1b0674a49f44fd46a0](https://user-images.githubusercontent.com/1992842/219980457-f1dc1b47-2d9a-42c4-8493-e323f8847ea2.png)

![66e9c1d1173b08d2cd50f1d7a1bb0a7dc632a3fc](https://user-images.githubusercontent.com/1992842/219980467-b4a07f9a-b7e5-4c87-adcf-f5e1a278a552.png)

![12e7b32d680e2dab0abd6f55a35cc25d312d79f3](https://user-images.githubusercontent.com/1992842/219980487-0fbc0bf4-08ca-4b1a-a17a-9bd86d6972e8.png)

![1ed1973c8609c62daf955a4b6939dc29ffa5b7bd](https://user-images.githubusercontent.com/1992842/219980516-e9deeec5-a564-49ee-bb06-91fc96edcaba.png)

**Comment by etienne07C1** [comment]
Same thought... we all agree this tool is amazing. 
We just note FR are immediately closed (as mine was) which can look a bit harsh...

**Comment by luckman212** [comment]
@exelban Got the new 2.8.10 version, thanks for the E/P custom colors, nice solution!
