### ISSUE TITLE
[Feature Request] display the uptime in the CPU menu

### ISSUE THREAD

**Issue by gianpaj** [exelban/stats#1398]
Similar to iStat menu

![image](https://user-images.githubusercontent.com/899175/230322495-cbe82b08-597e-41ae-93b8-b23169367765.png)

Sometimes it's useful to reboot a Mac computer, and I generally check the uptime to know if it's been over a week :)

Thanks a lot for this great app! 🙏

**Comment by exelban** [comment]
there is uptime in the dashboard

**Comment by gianpaj** [comment]
found it . thanks 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/899175/230336684-d20a0a71-151e-4b61-b700-7d6e4188ea50.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/899175/230336437-9634be1e-cfe2-4cca-8d44-84359ccfd9c2.png">

**Comment by mx1up** [comment]
as @gianpaj points out, it's not very discoverable. 

You have to open one of the widget you already have, click on the cog to go to settings, click on dashboard (because it's not selected by default), then scroll down (because the window is not resizable)

That is 4 actions vs 1 if it could be shown in one of the menu popups (like in iStat).
