### ISSUE TITLE
2 bugs in disk module

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1437]
Mac Studio, Ventura 13.3.1
iMac 2017, 13.3.1
Stats 2.8.18

1. I noticed some discrepancy in the behaviour of the Disk popup -> Top processes: 
On the iMac the Top processes update every second, on the Mac Studio they update only every 10 seconds
Both modules are set up exactly the same: 5 Top processes, 10 sec update interval. 
Changing the update interval on the Mac Studio seems to have no effect (stays at 10 seconds). The widget updates every second. 

2. Mac Studio: When I first used 2.8.18 yesterday the Temperature for "Macintosh HD" in the Disk popup was the same (but rounded up) as what was displayed in the Sensors popup -> NAND. 
Today the temperature is stuck at "22°C" and does not change at all. Sensors -> NAND shows 26.0°C and moves up and down a bit as expected.

**Comment by LostInCompilation** [comment]
Just wanted to report the first issue as well.
The Update Interval setting has no effect on the Drive widget. The values in the menu bar update every second.

**Comment by exelban** [comment]
1. There is no option in the app to change the top processes update interval.
2. There is no relation between the temperature in the Disk module and any of sensors in the Sensors module.

**Comment by valynor** [comment]
1. there's a clear difference between 2 machines with the same settings
2. 2. the temp value didn't change for a whole day

there are clearly some bugs here, even if you apparently chose to ignore them

**Comment by exelban** [comment]
1. You think that there is some difference. But there cannot be any difference. The reader runs every 1s. The only difference is in `ps` output. If there is no data for a few seconds, or minutes you will see no changes in the popup. It's a reason why I refuse for such a long time to implement that. Because I have no impact on how that works. And after I must explain each time why "it does not work as someone expect".
2. It could stack only if the NVMe SMART plugin does not return the data.

**Comment by valynor** [comment]
With the latest update 2.8.19 the disk popup now updates the top processes every second on my Mac Studio.

**Comment by exelban** [comment]
Hi. Yeap, you were right. There was a bug. Unfortunately, I was testing that on the build that has a fix. And didn't notice that(
