### ISSUE TITLE
[Feature Request] Automatically displaying Read/Write Speed of external drives on menu bar

### ISSUE THREAD

**Issue by xuanphongle** [exelban/stats#1576]
Hi, just made the transition from iStats and thank you so much for providing a great option!

My workflow includes a lot of backing up files between various external devices, and while I see that there is an option to pick which drive's R/W speed to display on the menu bar, IMO it would be more straightforward to be able to see the total data transmission speeds on the menu bar and then clicking on it to view each drive's speeds. 

Also I think the current UI for the Disks popup menu is splended, though there are some minor bugs such as the histogram overlapping with the R/W speeds rendering it impossible to make out when copying files. There are also some instances where I'm copying from an SD card to a HDD and it only displays activitity on the SD card while the HDD shows 0 on both read and write. 

Hope you will take my suggestions into consideration, will be buying you a ko-fi later, thanks for the great work.

Phong

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There is, just specify an active disk in the disk module settings.
Looks like you have need in some tool that more about disk monitoring than just wide usage monitoring. I cannot cover all use cases in the app (and don't even want or have time for that).
Could you share some screens with overlapping, because I never faced something like that?

I/O activity data depends on the drive drivers, and I cannot do nothing if there is no data.
