### ISSUE TITLE
Some Widgets occasionally missing on bootup

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1789]
Mac Studio M1 Max, macOS 14.2.1, Stats 2.9.21

I just booted my Mac and when Stats started up the CPU widget was missing in the menu bar. All of the other widgets (Sensors, GPU, RAM, Drives, Network) were present and working. 
Quitting and restarting Stats fixed it. 

I had this happen before about 1 month ago, at that time only the Network widget was missing.

**Comment by xeron** [comment]
Same, CPU widget often disappears for me too on M2 mac. Toggling the widget off/on fixes it for me.

**Comment by FabulousCupcake** [comment]
I've been having the same issue since several weeks ago as well

* I thought it was not playing nice with [Bartender](https://www.macbartender.com/Bartender5/), but finally got around to test a bit and even with it disabled, some widgets are usually missing (sometimes all)
* There's no particular buggy widget — sometimes all of them are gone (I have cpu, disk, and sensor)
* Quitting and starting Stats.app again do not always fix it
* Going to configuration page and hitting ⏸️ and then ▶️ always fixes it

**Comment by exelban** [comment]
hi. With the last update that problem must disappear.
