### ISSUE TITLE
Can not show the battery level of bluetooth keyboard

### ISSUE THREAD

**Issue by jack24254029** [exelban/stats#1885]
Can not see the battery level of bluetooth keyboard

![image](https://github.com/exelban/stats/assets/13265628/a34878cb-5f76-4687-a37f-d5c5eb0b7d1c)
![image](https://github.com/exelban/stats/assets/13265628/5a4dc933-535e-434e-ab45-15e3bfb554b2)
![image](https://github.com/exelban/stats/assets/13265628/8c6e19b9-ae91-4461-a647-90cb9e69d3cf)

 - Device: Mac mini 2023
 - macOS: 14.4.1
 - Application version: 2.10.7

**Comment by igorsantos07** [comment]
The same happens with my mouses. As a test, I connected a Logitech MX Master 3 (which doesn't even show up on the widget, nor is disabled in the Stats settings) and a generic one from AliExpress:

![image](https://github.com/exelban/stats/assets/532299/623602ff-9eb7-4573-97f1-0fcdf9d382f9) ![image](https://github.com/exelban/stats/assets/532299/daca3195-4247-423d-848d-cb7ac97058fd)

Mine is an Intel Core i5-8500B, same versions as the OP, and using the standard bluetooth chip.

**Comment by exelban** [comment]
Hi. I have to take a look at that. And there is not so much I can do. Looks like Apple broke the best API that gives BLE percentage. Looks like for now there is no good API for ble.
There always was a problem with getting a BLE percentage. And now I'm thinking about dropping this module support. Because there is no good way to get this information(

**Comment by jack24254029** [comment]
I think can only show the battery level about apple product for now, ex: Magic Trackpad, Magic Keyboard
Other ble devices can wait.
