### ISSUE TITLE
Network activity control

### ISSUE THREAD

**Issue by jeromepacman** [exelban/stats#1943]
Hi
It seems that on "network" module, the activity threshold no longer works.
It appeared on the previous version (before today's)

MBP14 M2 - Sonoma 14.4.1

**Comment by exelban** [comment]
Hi. I have checked that right now and it works. Could you recheck please?

**Comment by Nicopalameji** [comment]
I've also noticed that the activity threshold no longer works. 

But i think the issue is that the widget is not accurately displaying the graph of the network traffic. 

The graph in the panel seems to be accurate. 

<img width="274" alt="Screenshot 2024-05-14 at 18 50 21" src="https://github.com/exelban/stats/assets/145207003/8319b736-3878-4462-8d05-73c07063cc23">
<img width="274" alt="Screenshot 2024-05-14 at 18 44 26" src="https://github.com/exelban/stats/assets/145207003/65960934-2bef-4849-93a0-ae4419157219">


MBP14 M2 - Sonoma 14.3.1

**Comment by jeromepacman** [comment]
> Hi. I have checked that right now and it works. Could you recheck please?

I have rechecked and also flushed the prefs file.
There's currently a threshold

<img width="244" alt="Capture d’écran 2024-05-14 à 19 20 49" src="https://github.com/exelban/stats/assets/32860993/f07c2479-0b0b-4d51-80bf-40095485a382">

**Comment by exelban** [comment]
oh. This is a threshold for widgets only.
