### ISSUE TITLE
Feature request: Charging indicator for Battery

### ISSUE THREAD

**Issue by iliakukharev** [exelban/stats#213]
Would be great to see the lightning icon on the left of Battery "56%", like "⚡56%" when MacBook is charging.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.

There is a lightning icon when the battery widget selected.

**Comment by iliakukharev** [comment]
Yes, but not when the "Numbers" mode selected
![image](https://user-images.githubusercontent.com/13415594/101292188-03926700-381f-11eb-9e47-2bcee6b9a12f.png)

**Comment by exelban** [comment]
Oh, I see.
Unfortunately, it's not possible to add lighting to this widget. The reason is simple. All text widgets must look the same. Also, it cannot be lighting as emoji. Because it will look too unnatural in the menu bar.

The only way to add some lightning to this view. It's writing a new widget for the battery and draw manually lightning. But I don't want to provide too many different widgets. It allows reducing bugs and makes support easier.

Sorry, but it cannot be implemented.

**Comment by iliakukharev** [comment]
What about any other notification like `*56%`? Or `56%*`

**Comment by exelban** [comment]
Unfortunately in this widget, there is no option to add something.
If I add some symbol like `*` to show the charging state. After releasing someone will ask to "fix" with lightning or plug)
And I will have no option after. Because `*` does not have sense even for me.

**Comment by exelban** [comment]
I would really recommend switching to the battery widget. It can show not only the percentage but also the time to charge/discharge.

**Comment by iliakukharev** [comment]
Thank you for the explanation.

As for the widget, I like this one, but it does not have %
![image](https://user-images.githubusercontent.com/13415594/101294027-c8dffd00-3825-11eb-8fcb-5f9b0e936014.png)

**Comment by iliakukharev** [comment]
ah sorry. I'm blind. didn't see the options.
battery icon with additional info is the perfect option.
you can close this request :)
