### ISSUE TITLE
Apple could not verify "Stats.app" is free of malware

### ISSUE THREAD

**Issue by FelikZ** [exelban/stats#2152]
**Describe the bug**
After auto-update I can't launch the app anymore since Apple can't verify is genuine:
![image](https://github.com/user-attachments/assets/a31e7687-e5d3-4d80-b25b-d290ca2f6354)

I am using [homebrew cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/s/stats.rb) to manage Stats.app.

Any ideas?

**Details:**
 - Device: [Macbook Pro 2021 / M1]
 - macOS: [15.1 BETA]
 - Application version: [2.1.12]

**Comment by exelban** [comment]
I do not maintain the app in the brew, so I cannot help with that.
You can download the latest release [here](https://github.com/exelban/stats/releases/tag/v2.11.12).

**Comment by MyDogTom** [comment]
I confirm that downloading Stats directly from release page solves the problem.

Homebrew has an issue about this: https://github.com/Homebrew/homebrew-cask/issues/165584
Unfortunately, the error seems to be sporadic and hard to investigate. That's why Homebrew issue is also closed as `not planned`.
