### ISSUE TITLE
Sensor ordering - UX improvements

### ISSUE THREAD

**Issue by porg** [exelban/stats#2193]
## Genesis of the feature and its current implementation
- In #928 I proposed variants 1ab or 2. You went yet for another variant which I retroactively dubbed variant 3 (added it to the issue description there).

For the chosen implementation I have these usability problems and their solutions:

![Stats - Sensor order within Widgets - UX issues as of v2 11 15](https://github.com/user-attachments/assets/84a269a8-009f-4dbc-bfcc-fd97a0f37aef)

## 1) Technical shortnames barely recognizable
- Proposed: Use the human readable names as on the tab "Module"

### Status quo
- a) Limited in height (to 5 rows).
  - If you need to drag item °8 to position °1 this requires to move with stops inbetween and/or some drag'n'scroll. And all that with the technical shortnames which tell you nothing anyhow.
- b) Scrollbar within widget

### Proposed improvements
- a) unlimited height
- b) parent container gets the scrollbar

If you have many sensors you can use all available height for sorting then. Easily reorder far more than 5 sensors then.

## 3) Reordering is buggy
- Especially dragging an item to the top and bottom positions never worked as intended. As a workaround I positioned everything relative to position °2 and eventually took the auxiliary element °1 and moved it where it should be. Again not very WYSIWYG if you need to resort to such tricks.
- In some cases it did not perform the normal reordering behavior as in "insert dropped item at the target position and remove it from the source position" but instead "swapped the element currently at the target position to the destination position" which is a bug not a feature.

**Comment by exelban** [comment]
Hi. Thanks for such a nice proposal. But unfortunately, I must decline the proposition. The reason is very simple. Almost all that you propose requires custom components and I don't want to spend more time than needed to keep the app working and have no time for such not important improvement (from my POV). The keys are used on the list just because the whole settings - widget system works on key. And to implement some kind of sorting in this place it's limited to the keys and has no names for sensors.

TL.DR: I don't see a sense in spending days improving something that I use mostly once a year. It's good enough for me.
