### ISSUE TITLE
External SSD temperature monitoring

### ISSUE THREAD

**Issue by ctrl-shift-vs** [exelban/stats#2225]
**Feature request**

I would like to see my external SSD temperature as part of other sensor suite in menubar. The external SSD temperature can already be seen when in SSD menubar icon after clicking on the control icon (see image), but cannot be added to the Sensors icon suite (only one option for NAND, which must be internal storage). Please add this feature. Thanks!!

<img width="281" alt="Screenshot 2024-11-16 at 10 07 57 PM" src="https://github.com/user-attachments/assets/a44d289d-fc09-467a-9b41-33d247dc1b5d">

**Comment by exelban** [comment]
It's not possible. This value is available only in Disk module. And it cannot be added to the Sensors module.

**Comment by beckxie** [comment]
Hi @ctrl-shift-vs , 

I also had the same need to display disk temperature.
Since the current sensor widget does not support it, I made a simple implementation by modifying the Disk widget to show temperature instead of usage.

![Image](https://github.com/user-attachments/assets/e92d7fe1-be00-4fc0-924d-00aa77c669be)

However, my approach is an intrusive modification, so it’s not suitable for merging into the upstream repository. 
Perhaps @exelban could consider officially adding this feature to the Disk module in the future.

For reference, here are the details: https://github.com/beckxie/stats/pull/1
