### ISSUE TITLE
Drains MacBook Pro (intel silicon) battery

### ISSUE THREAD

**Issue by jsr-coffee** [exelban/stats#2263]
Observed significant decrease in battery life (from 7-10h down to ~45min) when Stats is active. Took a couple months to isolate through A/B testing with various apps/processes. Key observations:

- Seems to have a multiplier effect. The more processes and apps that are running WHILE stats is also running, the more pronounced the battery drain. Perhaps some process associated with Stats is causing other processes (e.g. processes associated with browser tabs, vs code, excel) to do more and consume more battery.
- Seems to drain while laptop is closed in transit - perhaps Stats is preventing Sleep?

These topics are beyond my understanding but I've done my best to observe over the past few months that I've had Stats installed.

**Comment by exelban** [comment]
hi. Yes, there were a few reports with similar problems. In all cases, the problem was not in Stats but in the `top` or another 3d party cli that is used in the Stats. Unfortunately, it cannot be fixed since without these dependencies Stats will have no data to show. So no workaround here helps. You can try to disable top processes in all modules and see if it helps.
