### ISSUE TITLE
Add close button to detached windows

### ISSUE THREAD

**Issue by blackketter** [exelban/stats#282]
As discussed in #272, I suggest that there be a way to close windows that have been torn off the menubar.  

I suggest that they should use the standard macOS window controls in the top-left of the new window.   The two buttons for Activity Monitor and the settings window could be relocated to the bottom of the window, like this:

![closebuttons](https://user-images.githubusercontent.com/131679/104134103-73bf6b80-533c-11eb-851d-8ecaff6323d4.png)

This seems to be a common pattern for other menubar apps, like Fantastical.

Alternatively, the buttons could be put in the upper right corner, but this may appear too cluttered:

![closebuttons-2](https://user-images.githubusercontent.com/131679/104134323-ab7ae300-533d-11eb-9b00-923c9e9d0e60.png)

Also: Clicking on either the settings or Activity Monitor buttons should not close the window, leave that for the close button.

**Comment by exelban** [comment]
Thanks for the propositions.
First option not acceptable at all. I will don't want to have different layouts for pinned and unpinned views.

The second one is a little bit better. But there will be only a close button. Also, it cannot be the default system buttons. It must be a custom one. Because: a) it will be not centered, b) it will close the whole window, and there is a different mechanism for close the popup

**Comment by blackketter** [comment]
Gotcha.  I stole the buttons in the mockup from System Preferences which has all three buttons even though only two (close and minimize) will ever be active.  Minimize is probably not going to be used often, so a single close button is probably sufficient.  I was just trying to use the system default behavior.

The close button(s) could appear only when you drag the window away.  This would make the popup window appear less complicated in the typical use case.

Thanks!

**Comment by blackketter** [comment]
Works great, thanks!
