### ISSUE TITLE
Reload public IP address

### ISSUE THREAD

**Issue by sam-anam1** [exelban/stats#339]
hello @exelban again

it would be really great that has reload icon to recheck IP or could be submenu for refresh

its 'cause sometime IP change or connected to VPN that in need to copy the IP as clickable to copy to clipboard

my suggestion or maybe it could two icons 🔄 and copy icon  beside as its clickable (to copy to clipboard)

**Comment by exelban** [comment]
Hi.
To implement this feature I need to make a new UI for IP addresses. Because now there is no option to add the button like this. New UI for addresses will solve not only this problem but an existing one (#307).

Ping me, if someone has an idea of how it could be implemented. 
I'm thinking about a new section in the Network popup with `Addresses`. There will be public and local IPs (ipv4 and ipv6), an option to reload them.
