### ISSUE TITLE
Feature Request: Controllable fan toggle in sensors dropdown.

### ISSUE THREAD

**Issue by hsuehpascal** [exelban/stats#431]
Hi,

First off, thank you so much for the amazing, all-in-one app!

I was wondering since there is the functionality to control fan speeds in the Fans dropdown menu, will it be possible to integrate the same function to the Sensors menu if one chooses to show the fan speeds there, or to maybe combine the two because, after all, one should want to adjust fan speeds only when the temperature gets out of hand?

**Comment by exelban** [comment]
Hi.
No, there will be no fan control in the sensors module. I'm trying to keep these modules as simple as possible.
There is a separate module for fans because it's a little bit different than sensors. Especially in the apple silicon.
Even more, I have a plan to remove fans from the sensors module. Because it makes some complications with the widget.
