### ISSUE TITLE
Feature request: Show system on time on battery item.

### ISSUE THREAD

**Issue by kevindiu** [exelban/stats#450]
It would be nice if the system on time shows on the battery drop-down detail.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/1985382/116655423-06584900-a9c6-11eb-803a-93deca3f4708.png">

**Comment by exelban** [comment]
Hi. Thanks for the proposal. I think you mean time from last boot. If yes - it could be found in the dashboard.

**Comment by kevindiu** [comment]
Yes I found it on the dashboard, but I think it may be more convenient if we can see it there.

**Comment by kevindiu** [comment]
Also it may be useful if we show the `System on time since last charge".
I can help translate it to Traditional Chinese and Japanese.

**Comment by exelban** [comment]
The last boot cannot be placed in the battery module. Because there are macs without batteries. And these users want to see this parameter (I want to see).

System on time since the last charge - it's a little bit hard to determine. It cannot be read from the system. It can be easily implemented in the Stats. But it will be more "since last power adapter".

**Comment by kevindiu** [comment]
thank you for your quick response. 
For Macs without battery, we can consider to hide it on the menu.

Yeah I think `since last power adapter` is good enough.

BTW just an idea, for `System on time since the last charge`, we can implement it by writing a time to the database every minute, and base on the time the data written, we can calculate the system on time.
