### ISSUE TITLE
Blank space of sensor and fans symbols too large

### ISSUE THREAD

**Issue by leachimus** [exelban/stats#483]
Since the last two or three updates, the white space in the icons is way too big. This looks very unattractive in the bar. Please reduce the spacing again. Thanks

<img width="265" alt="Sensors_Text 2021-05-15 17-06-01" src="https://user-images.githubusercontent.com/76697859/118366209-17957e00-b5a0-11eb-86f9-ef48adcbbf1b.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It's because previously the size of these widgets was dynamic. And not it's fixed.
There was a several reason for this. And also was a few asks for fixed width (#348).

**Comment by exelban** [comment]
Hmm, I have an idea how it can be solved.
I can add an option: fixed width. The widget width will be dynamic by default. Based on widget value. And this option will make the width static.

I'm not sure if it's will be a good solution. Because of: #453 and #136. These crashes were connected to this widget width at some way.

**Comment by leachimus** [comment]
Thanks for the support. It is worth a try. I will test and report. 👍

**Comment by leachimus** [comment]
Work very fine until now, thaks for fix it!
