### ISSUE TITLE
Feature Request: All-In-One Menu Bar Icon

### ISSUE THREAD

**Issue by SteradianAdrian** [exelban/stats#500]
There could be an option that merges every stat into one. Having separate icons for every stat can really fill up your menu bar.

Maybe similar to how _Stats Panel_ does it:
![Screen Shot 2021-06-08 at 10 08 52 PM](https://user-images.githubusercontent.com/84081003/121282919-47d2f280-c8a8-11eb-947c-3d5e7ad6010d.png)

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
Sorry for the long response, but I needed some time to think about it.

In theory, it could be implemented. But there are a few moments:
- when this view will be visible (on each widget, when all widgets disabled and when app icon left in the menu bar etc)
- new UI/UX
- which elements of each module must be presented there

For me, it looks like it must be a separate app. Because Stats actually has a different way of use than an app with a fuature like this.

**Comment by asyba** [comment]
> Hi. Thanks for the proposal. Sorry for the long response, but I needed some time to think about it.
> 
> In theory, it could be implemented. But there are a few moments:
> 
> * when this view will be visible (on each widget, when all widgets disabled and when app icon left in the menu bar etc)
> * new UI/UX
> * which elements of each module must be presented there
> 
> For me, it looks like it must be a separate app. Because Stats actually has a different way of use than an app with a fuature like this.

so its going to be implemented or you are still thinking?

**Comment by exelban** [comment]
@asyba I think it will be implemented someday.
