### ISSUE TITLE
Add label option for network graph in menu bar

### ISSUE THREAD

**Issue by simondemartini** [exelban/stats#572]
The network chart doesn’t seem to have the same option to have a label included in the chart that the CPU, RAM and other line charts to. Can a label like “NET” be added to match?

![CFE2C46E-783C-4509-B33A-4AEBB0244EB6](https://user-images.githubusercontent.com/279847/127942426-43a9b291-0041-40c4-87f9-2dd69d3301d3.png)
For example: The network chart looks out of place here without a label.

There is an existing option for a separate “NET” label widget though, but that is separate from the graph widget so it has more spacing and doesn’t match the others.

**Comment by wfrank21** [comment]
You can add the NET label in the Network modules settings. 
![image](https://user-images.githubusercontent.com/73826476/127987460-64b9794b-01af-4169-b14f-6476e00c52c1.png)

**Comment by exelban** [comment]
Hi. Thanks for the report.
Yes. The network chart does not have this option. Because CPU/RAM it's a different widget than in the Network. But I think it could be added to be more uniform.

@wfrank21 yes, but @simondemartini talking about label near chart. It's has a little bit different view than the `label` widget. Because on macOS 11+ the widgets have internal paddings adding by the system. So label widget and label near widget look different. There is no this problem on < macos 11, because there are no paddings between widgets in the menu bar.

Label widget:
<img width="77" alt="Zrzut ekranu 2021-08-3 o 11 02 21" src="https://user-images.githubusercontent.com/13332412/127988845-6ad8e997-1371-4bf2-8b37-19189de2b087.png">

Label option in the widget:
<img width="74" alt="Zrzut ekranu 2021-08-3 o 11 02 38" src="https://user-images.githubusercontent.com/13332412/127988887-37694845-fa4c-4e05-af17-ba26c5175c9f.png">
