### ISSUE TITLE
Feature Request: "Update Frequency with Panel Open"

### ISSUE THREAD

**Issue by Panini** [exelban/stats#590]
**Update frequency** 1sec is a little cpu intensive, so I use higher values.
But sometimes I want to monitor something in real time (1sec), and by then I've usually clicked the menubar icon already and have the **panel open**.

- (for example I wanted to monitor DC-in wattage in real-time to see how quickly (if at all) it takes to reach max charging speed)

**Details:**
 - Device: [Mid 2017 15" Macbook Pro]
 - MacOS [10.15.7]
 - Application version [e.g. 2.6.5]

**Comment by exelban** [comment]
Hi. Do you propose to have another option that will change the update interval when the popup window will be opened?

**Comment by Panini** [comment]
> Hi. Do you propose to have another option that will change the update interval when the popup window will be opened?

Yup!

**Comment by exelban** [comment]
Sorry but it's not possible. It will require rewriting at least half of the app.
And I don't think that it's a good feature to implement at all. Because it's such unexpected behavior. If CPU must update every second. It must update every second always. And not in some cases, it must update faster or slower.
