### ISSUE TITLE
Indicate in the menu on the left which elements are enabled

### ISSUE THREAD

**Issue by Angelk90** [exelban/stats#648]
**Describe the bug**
Indicate in the menu on the left which elements are enabled, will see the example image.

<img width="721" alt="Schermata 2021-09-26 alle 19 30 45" src="https://user-images.githubusercontent.com/20476002/134817979-e9006b7a-72b1-4f76-8f63-de2fcb75d24c.png">

**Details:**

- Device: MacBook Pro 13" (Mid 2020)
- macOS: macOS Big Sur (11.5.0)
- Application version: 2.6.12

**Comment by exelban** [comment]
Hi.
The logic is separated. On the left side, you have a menu, and on right, you could enable/disable the module.
I don't see the necessity to show status in the menu. Only if moved here the toggle button. Which will not be implemented. Because this functionality will leave on the right side of the window.
