### ISSUE TITLE
Fan control show "automatic" after reboot, should show "snowflake"

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#699]
**Describe the bug**
When fans were set to max (*), the fan control will show "Automatic" after the reboot. The fans will still spin at max speed.

**Before the reboot:**

<img width="300" alt="Screen Shot 2021-11-15 at 7 05 43" src="https://user-images.githubusercontent.com/8013017/141725868-17823673-491b-4ef2-9861-d343d866d357.png">

**After the reboot:**

<img width="296" alt="Screen Shot 2021-11-15 at 7 06 59" src="https://user-images.githubusercontent.com/8013017/141725882-66005e80-2b54-4538-9ca7-0ab6d248d332.png">

**Solution:**
Clicking on the (*) symbol and back to "Automatic" actually sets the control back to automatic.

**Details:**
 - Device: Macbook Pro 16 2019
 - macOS: 12.0.1
 - Application version: 2.6.19

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will take a looks at this bug.

**Comment by exelban** [comment]
Hi. It looks like some bug in the SMC. Because normally macOS will reset fans when reboot. It works fine in sleep mode. The reason why you see `Automatic` mode after reboot, it's because the fans report that they are in the auto mode. But for some reason, the fan's value was not reset before rebooting by macos.
I'm not sure I can do anything with it.

**Comment by richardtop** [comment]
Ok, then feel free to close it.

**Comment by exelban** [comment]
I will keep tracking this bug and hope it will be fixed in the near future. If not, I will try to do something with this.
