### ISSUE TITLE
Feature Request: Weather/Temperature

### ISSUE THREAD

**Issue by techx-guy** [exelban/stats#743]
I would love it if you could add a little weather icon with temp using an open source weather API like openweather or something. Nothing crazy just a simple temperature would be amazing! Thanks for all your hard work, this application is amazing.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I was sure that there was already a feature request like this, but no.
I don't think that it will be a good feature for this app. Because this is monitoring for mac. Also, there is a nice open-source app that shows weather in the menu bar. I'm not sure I can do it better.

**Comment by techx-guy** [comment]
Gotcha, totally understand. What is the name of that open-source menu bar app for the weather?

**Comment by jnvillar** [comment]
this would be nice though
