### ISSUE TITLE
Latest update (2.7.0) missing temperature sensors on M1 MacBook Air

### ISSUE THREAD

**Issue by chriskalos** [exelban/stats#794]
After updating to version 2.7.0 of Stats on M1 MacBook Air, the temperature sensors don't even show up in the menu and the temperature widget doesn't work in the title bar.

![image](https://user-images.githubusercontent.com/9339301/149665117-591d70fc-6692-44c8-b29d-55f9fa9d0269.png)
![image](https://user-images.githubusercontent.com/9339301/149665127-95aabd8c-7e8b-4425-aa77-de0724dd40d1.png)

**Comment by exelban** [comment]
Hi. You need to enable HID sensors in the settings in the [new version](https://github.com/exelban/stats/commit/98ee87fbf81924e672794a021afed161b0d1f5cd).

**Comment by exelban** [comment]
The reasons why it's these sensors are disabled by default:
- it's available on M1 and looks like some sort of "hack". Because before m1 normally all sensors were in the SMC, and in the new M1 pro/max is again in the SMC
- these HID reader takes more CPU usage than all other modules together

But I will try to make it enabled by default only for the M1 macs.

**Comment by bt61** [comment]
I just updated and noticed this immediately.  When I enable HID it shows two temperatures, but I can't tell which they are and see no way to set which display here like before.

**Comment by trinquity** [comment]
It's probably the same thing @exelban but after system update Sequoia 15.1.1 (24B2091) this happened again with my M4. Only few sensors are available right now. But it was okey with Sequoia 15 I was able to see CPU/GPU Sensors.
Sharing the sensors after osx 15.1.1 update
<img width="392" alt="Screenshot 2024-12-08 at 15 21 24" src="https://github.com/user-attachments/assets/67740e72-1fad-40bc-b9a6-b3998fd2fe81">
