### ISSUE TITLE
Process item may be duplicated when item is selected

### ISSUE THREAD

**Issue by reekystive** [exelban/stats#798]
When I selected the process `Stats` in CPU details list, another `Stats` process may appear in the list:

<img width="392" alt="Screen Shot 2022-01-17 at 20 42 50" src="https://user-images.githubusercontent.com/26853900/149772019-5adc5144-91ef-42e0-9fd9-54edf33b32f3.png">

But actually there is only one `Stats` process:

<img width="1101" alt="Screen Shot 2022-01-17 at 20 43 51" src="https://user-images.githubusercontent.com/26853900/149772113-d7c4e0b0-a38d-4b89-b99c-d862ad0b50e5.png">

**Details:**

 - Device: MacBook Air (M1)
 - macOS: 12.1
 - Application version: 2.7.0

**Comment by exelban** [comment]
Yes, it could be duplicated. Because you have pinned the position. And in the next moment, this process could be in another position. But you still could stop the selected process. It's mostly only for this.

**Comment by reekystive** [comment]
If I pinned its position, it should always be there and be excluded in other items, I think maybe this would be better?

**Comment by exelban** [comment]
I will need to stop the update all processes in this case. Locking the process is only for killing the selected process. Because without that you can click on the process with position 2 but at the same moment the processes list will update and you kill another process (if someone is now on position 2).
