### ISSUE TITLE
Network: Changing reader type messes up total upload and download

### ISSUE THREAD

**Issue by burneyy** [exelban/stats#908]
**Describe the bug**
I noticed that changing between the "Process based" and "Interface based" Reader type setting in the Network module messes up the total upload and total download.

Today, I have accumulated a total download of 3.1GB and a total upload of 150MB before playing with this setting.
After changing from "Interface based" (original setting) to "Process based", I noticed that the total upload had doubled to 300MB.
Vice-versa, when changing back to "Interface based" the total download has doubled to 6.2GB.
Now, whenever I change to "Process based" another 150MB is added to the total upload - and whenever I change to "Interface based" another 3.1GB is added to the total download.
You can also see this in the usage history as shown below when changing twice between those settings.
![Screenshot 2022-04-11 at 16 55 12](https://user-images.githubusercontent.com/7356251/162767824-3247abb3-f3fc-4120-91ea-1f42d6f831f1.png)

**Details:**
 - Device: MacBook Pro 13" (Mid 2015)
 - macOS: 12.3.1
 - Application version: 2.7.12

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
I will check this behavior.

**Comment by exelban** [comment]
Hi. I figured out why it's happening. It's because the interface reports not the i/o from the last read, but from start. So, when changing the reader type, the app saves the actual value of stats. And on the next read, it correctly shows the i/o because it can calculate the diff. I'm not sure it needs to be fixed, the one I can do, it's reset the total download/upload when changing the reader type.
