### ISSUE TITLE
RAM widget and popup don't show the same value

### ISSUE THREAD

**Issue by valynor** [exelban/stats#933]
The RAM % widget and the value shown in the popup are sometimes different (off by 1%, rounding error?). 
Update interval is 1 second, it's not that. 

![Screenshot 2022-05-08 at 20 04 07](https://user-images.githubusercontent.com/23384233/167309333-9f12db48-aac9-4141-8373-a956cf8236a3.png)

**Comment by exelban** [comment]
Hi, Thanks for your feedback.
I will recheck this. It could be or different rounding mechanism. Or update mechanism (the popup is not updating when closed).

**Comment by zigapovhe** [comment]
Hi! I can replicate same thing with CPU widget. My guess would also be different rounding mechanism because both values are updating at the same time (it just differs in value sometimes). Network widget looks fine.

<img width="258" alt="Screenshot 2022-05-17 at 13 42 56" src="https://user-images.githubusercontent.com/21365070/168803444-a420fd4a-b866-4e03-8753-ac3375d5e055.png">
