### ISSUE TITLE
Preventing Sleep

### ISSUE THREAD

**Issue by jasonkylejacobs** [exelban/stats#981]
I've installed Stats on my 2011 iMac that's running High Sierra, however I've noticed that it seems to be preventing my iMac from sleeping. I've confirmed this by checking the Energy tab in Activity Monitor, which is showing Stats to have the highest Energy Impact of all running apps, and also shows that Stats is preventing sleep.

Is this a potential bug, or is there a setting that I have set incorrectly?

Thanks :)

**Comment by jasonkylejacobs** [comment]
No problem, thanks for your speedy response! 

Here are a couple of screen shots from Activity Monitor, showing the CPU tab with CPU usage and Idle Wake Ups, and the Energy tab with Energy Impact and Preventing Sleep status.

The CPU usage seems to fluctuate around the 2-5% region.

![stats1](https://user-images.githubusercontent.com/14262984/176013801-2f9ef7a4-b473-4b92-8d23-35ea6abd2999.png)

![stats2](https://user-images.githubusercontent.com/14262984/176013839-161201e8-7ddd-4c7c-9a4b-dbbdc72fca8d.png)

**Comment by exelban** [comment]
Hmm, CPU usage looks fine. I have no idea why the Energy impact is so big. Also strange that the activity monitor shows that Stats can prevent sleep.

Ohh, high sierra. Sorry, I didn't notice. Yeap, there was a report that some users have a problem with that. I can't do anything with that. You need to update your mac for normal work of Stats. Because High Sierra supports only nominal. Some users ask for that. But it does not have support.

**Comment by jasonkylejacobs** [comment]
Okay, that's no problem. Unfortunately I can't upgrade the OS, as the Mac is too old, so I'll have to make do. Thanks for your help with this :)
