### ISSUE TITLE
[Feature Request] Add button to close all chart open for specific module 

### ISSUE THREAD

**Issue by kevinm6** [exelban/stats#986]
I think it could be nice add a single button (maybe a disclosure next to the popup title) that close/open all the chart (StackView) for a specific module (especially “Sensors”).

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I don't see a good reason for this button. It's easy to close 10+ charts as open them. And I don't want to invent a new mechanism for that type of button. I just don't see any reason for that.

**Comment by kevinm6** [comment]
Ok, I get what you mean.
I was just thinking that (like tree folders) use a disclosure to toggle all the stack view could be useful, even because the are not reset to hidden by default when showing again the popup... and since, unlike iStatMenus, graph appears when you click instead of showing a popover with it.

So, you don't accept even a PR, in case?

Thank you for the reply and the amazing work on this app, btw.

**Comment by exelban** [comment]
Hi.
I take a look at how it can be implemented. It's possible, but it requires too much work for such a small feature.

The problems related to this feature:
- it cannot be just a button "hide all charts" because it must be visible only when at least 1 chart is opened
- ok, it can be a toggle button that will be visible all time but open/close all charts depends... and depends on what? For example, if you have opened one chart, this button must open all charts or close one opened? Every user will have his own opinion on that point.
- it must be a separate button for each kind of sensors
