### ISSUE TITLE
[Feature Request] Group stats together (general overview) under one icon

### ISSUE THREAD

**Issue by DomBot1** [exelban/stats#991]
Hey,
I appreciate how much system information this app provides.
However I'm missing an option of some basic overview under just one icon in the menu bar. The problem is that I have several other icons in the menu bar and since each of the categories (RAM/CPU/GPU...) is split into separate icons, it clogs the menu bar and I can't even fit them all in there.
Thanks!

**Comment by exelban** [comment]
Hi. Thanks for the proposal.

I'm currently working on a similar feature. But it will not be one view for all widgets. But one view per module. 
One view for all modules it's not possible because: need to have one popup view for all modules (that I don't have) and the implementation of one view is hard to realize with the current code base.
